# .github/workflows/release.yml

name: Release

on:
  release:
    types: [published]

jobs:
  attach-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: windows_grundskript.ps1 zum Release hinzufügen
        uses: softprops/action-gh-release@v2
        with:
          files: windows_grundskript.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
